// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB--W4KYXtfOqKMhtdsvrgxr6yz0M3m8aY',
    appId: '1:850662307251:web:0835fde39d8f3f60f647c6',
    messagingSenderId: '850662307251',
    projectId: 'apps-flutter-8f963',
    authDomain: 'apps-flutter-8f963.firebaseapp.com',
    storageBucket: 'apps-flutter-8f963.appspot.com',
    measurementId: 'G-YD591Y4G6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVB8E2iIYolaRe9dzPCMFn4zCpYKjEpU',
    appId: '1:850662307251:android:dbb6d36fedf494c4f647c6',
    messagingSenderId: '850662307251',
    projectId: 'apps-flutter-8f963',
    storageBucket: 'apps-flutter-8f963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrEuewsbniLfRF-DWl5VnhUUfUTdZMqQ',
    appId: '1:850662307251:ios:fc4eef8df783b4acf647c6',
    messagingSenderId: '850662307251',
    projectId: 'apps-flutter-8f963',
    storageBucket: 'apps-flutter-8f963.appspot.com',
    androidClientId: '850662307251-hid239q7jecrqabbjav28lvvg8n7m9d2.apps.googleusercontent.com',
    iosClientId: '850662307251-rr4p9u6uduolhrgi6ku1iu9rjvj70r6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrEuewsbniLfRF-DWl5VnhUUfUTdZMqQ',
    appId: '1:850662307251:ios:70d65a163df84525f647c6',
    messagingSenderId: '850662307251',
    projectId: 'apps-flutter-8f963',
    storageBucket: 'apps-flutter-8f963.appspot.com',
    androidClientId: '850662307251-hid239q7jecrqabbjav28lvvg8n7m9d2.apps.googleusercontent.com',
    iosClientId: '850662307251-3int2d69ui8p6hhgjs6o59n2fb5pqeig.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
